# Generated by Django 4.1.5 on 2023-01-15 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='status', max_length=30, null=True)),
                ('grade', models.CharField(default='grade', max_length=30, null=True)),
                ('speciality', models.CharField(default='speciality', max_length=30, null=True)),
                ('salary', models.CharField(default='salary', max_length=30, null=True)),
                ('education', models.CharField(default='education', max_length=30, null=True)),
                ('experience', models.CharField(default='experience', max_length=30, null=True)),
                ('portfolio', models.CharField(default='portfolio', max_length=30, null=True)),
                ('title', models.CharField(default='title', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(default='email@mail.com', max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
